/** Compatibility re-exports — prefer `import type { … } from '@boardgame/shared'`. */
export type {
  AuthSuccessResponse,
  AuthUser,
  CollectionEntry,
  CollectionStatus,
  DiscoverUserRow,
  FriendConnection,
  FriendshipRelationship,
  GameDetail,
  GameReview,
  GameReviewsListResponse,
  GameListItem,
  GamesListResponse,
  CreateGameReviewPayload,
  UpsertGameRatingPayload,
  UpdateGameReviewPayload,
  MessageView,
  PaginatedMeta,
  PendingRequest,
  PublicProfileGamePreview,
  PublicProfileSummary,
  PublicUserCard,
} from '@boardgame/shared';
